In [4]:
import pandas as pd
import numpy as np

# Vectors and basic data types
die = np.array([1, 2, 3, 4, 5, 6])
print(die)
print(isinstance(die, np.ndarray))

five = 5
print(five)
print(isinstance(five, int))
print(1) # length of five
print(len(die))

int_values = np.array([1, 5], dtype=int)
text = np.array(["ace", "hearts"])
print(np.sum(int_values))
# print(np.sum(text)) # this would result in an error

print(die.dtype)

int_values = np.array([-1, 2, 4], dtype=int)
print(int_values.dtype)

print(np.sqrt(2)**2 - 2)
text = np.array(["Hello", "World"])
print(text.dtype)
print(np.dtype(str))

print(3 > 4)
logic = np.array([True, False, True])
print(logic.dtype)
print(np.dtype(bool))

comp = np.array([1 + 1j, 1 + 2j, 1 + 3j])
print(comp)
print(comp.dtype)

print(np.frombuffer(b'\x00\x00\x00', dtype=np.uint8))
print(np.frombuffer(b'\x00\x00\x00', dtype=np.uint8).dtype)

hand = np.array(["ace", "king", "queen", "jack", "ten"])
print(hand)
print(hand.dtype)

# no attributes equivalent in python numpy
# no names equivalent in python numpy

die = die + 1
print(die)

die = die.reshape((2, 3))
print(die)
die = die.reshape((3, 2))
print(die)
die = die.reshape((1, 2, 3))
print(die)

m = die.reshape((2, 3))
print(m)
m = die.reshape((2, 3), order='F')
print(m)

ar = np.array([11, 12, 21, 22, 31, 32, 13, 14, 23, 24, 33, 34]).reshape((2, 2, 3))
print(ar)

hand1 = np.array(["ace", "king", "queen", "jack", "ten", "spades", "spades", "spades", "spades", "spades"])
print(hand1.reshape((5, 2)))
print(hand1.reshape((2, 5)))

hand2 = np.array(["ace", "spades", "king", "spades", "queen", "spades", "jack", "spades", "ten", "spades"])
print(hand2.reshape((5, 2), order='F'))
print(hand2.reshape((2, 5), order='F'))

print(die.dtype)

# In Python, the type is 'numpy.ndarray' for numpy arrays
print(type(die))

print(type("Hello"))
print(type(5))
now = pd.Timestamp.now()
print(now)
print(type(now))

# unclass is an R-specific concept and doesn't have a direct equivalent in Python
mil = 1000000
print(mil)

# again, class concept is more R-specific
gender = pd.Categorical(["male", "female", "female", "male"])
print(type(gender))

# unclass is an R-specific concept
# as.character is R-specific too

card = np.array(["ace", "hearts", 1])
print(card)

print(np.sum([True, True, False, False]))
print(np.sum([1, 1, 0, 0]))

print(str(1))
print(bool(1))
print(int(False))

list1 = [np.arange(100, 131), "R", [True, False]]
print(list1)
card = ["ace", "hearts", 1]
print(card)

df = pd.DataFrame({
    'face': ["ace", "two", "six"],
    'suit': ["clubs", "clubs", "clubs"],
    'value': [1, 2, 3]
})
print(df)

deck = pd.DataFrame({
    'face': ["king", "queen", "jack", "ten", "nine", "eight", "seven", "six", "five", "four", "three", "two", "ace"] * 4,
    'suit': ["spades"] * 13 + ["clubs"] * 13 + ["diamonds"] * 13 + ["hearts"] * 13,
    'value': [13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1] * 4
})
print(deck)

deck.to_csv('~/open-source/r-projects/testr/cards_python.csv', index=False)


[1 2 3 4 5 6]
True
5
True
1
6
6
int64
int64
4.440892098500626e-16
<U5
<U0
False
bool
bool
[1.+1.j 1.+2.j 1.+3.j]
complex128
[0 0 0]
uint8
['ace' 'king' 'queen' 'jack' 'ten']
<U5
[2 3 4 5 6 7]
[[2 3 4]
 [5 6 7]]
[[2 3]
 [4 5]
 [6 7]]
[[[2 3 4]
  [5 6 7]]]
[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[[11 12 21]
  [22 31 32]]

 [[13 14 23]
  [24 33 34]]]
[['ace' 'king']
 ['queen' 'jack']
 ['ten' 'spades']
 ['spades' 'spades']
 ['spades' 'spades']]
[['ace' 'king' 'queen' 'jack' 'ten']
 ['spades' 'spades' 'spades' 'spades' 'spades']]
[['ace' 'spades']
 ['spades' 'jack']
 ['king' 'spades']
 ['spades' 'ten']
 ['queen' 'spades']]
[['ace' 'king' 'queen' 'jack' 'ten']
 ['spades' 'spades' 'spades' 'spades' 'spades']]
int64
<class 'numpy.ndarray'>
<class 'str'>
<class 'int'>
2023-10-12 21:04:24.208971
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1000000
<class 'pandas.core.arrays.categorical.Categorical'>
['ace' 'hearts' '1']
2
2
1
True
0
[array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 